"""Add products

Revision ID: d05442830cce
Revises: 4e7f84a34c9c
Create Date: 2026-08-16 21:01:43.046201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd05442830cce'
down_revision: Union[str, Sequence[str], None] = '4e7f84a34c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_audit_logs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.alter_column('config',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('crm_form_submissions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('data',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.create_index(batch_op.f('ix_crm_form_submissions_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'crm_forms', ['form_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('crm_forms', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('fields_config',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.create_index(batch_op.f('ix_crm_forms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_forms_uid'), ['uid'], unique=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'stages', ['stage_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'pipelines', ['pipeline_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.alter_column('options',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('sp_records', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['assignee_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('participants',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'cards', ['card_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'tasks', ['parent_task_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.alter_column('events',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('allowed_entities',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('allowed_methods',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.alter_column('result_log',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.alter_column('action_config',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.alter_column('action_config',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.alter_column('result_log',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.alter_column('allowed_methods',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('allowed_entities',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('events',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'tasks', ['parent_task_id'], ['id'])
        batch_op.create_foreign_key(None, 'cards', ['card_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.alter_column('participants',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('sp_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.alter_column('options',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('crm_forms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'stages', ['stage_id'], ['id'])
        batch_op.create_foreign_key(None, 'pipelines', ['pipeline_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_crm_forms_uid'))
        batch_op.drop_index(batch_op.f('ix_crm_forms_id'))
        batch_op.alter_column('fields_config',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('crm_form_submissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'crm_forms', ['form_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_crm_form_submissions_id'))
        batch_op.alter_column('data',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.alter_column('config',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_audit_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('entity_name', sa.VARCHAR(), nullable=True),
    sa.Column('actor', sa.VARCHAR(), nullable=False),
    sa.Column('actor_email', sa.VARCHAR(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
