"""initial_schema

Revision ID: ebb32388df81
Revises: 
Create Date: 2026-06-15 00:44:12.845362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb32388df81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.alter_column('config',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.alter_column('options',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('participants',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'cards', ['card_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'tasks', ['parent_task_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.alter_column('events',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('allowed_entities',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('allowed_methods',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.alter_column('result_log',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.alter_column('action_config',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.alter_column('action_config',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.alter_column('result_log',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.alter_column('allowed_methods',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('allowed_entities',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('events',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'cards', ['card_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'tasks', ['parent_task_id'], ['id'])
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'])
        batch_op.alter_column('participants',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('custom_fields', schema=None) as batch_op:
        batch_op.alter_column('options',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.alter_column('config',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
